server:
  port: 8091

spring:
  application:
    name: openAPI
    description: retrieves article data by articleNo

  h2:
    console:
      enabled: true
      path: /h2-console

#  datasource:
#    url: jdbc:h2:mem:test
#    driver-class-name: org.h2.Driver
#    username: sa
#    password: ""
#
  datasource:
    url: jdbc:mysql://localhost:3306/openAPI
    username: root
    password: Tasnim2017#
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari.connection-timeout: 30000

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL8Dialect


logging:
  level:
    org:
      hibernate: DEBUG
