openapi: 3.0.0
info:
  title: Article API
  version: 1.0.0

paths:
  /articles:
    get:
      summary: List all articles
      operationId: getArticles
      tags:
        - articles
      parameters:
        - name: limit
          in: query
          required: false
          schema:
            type: integer
      responses:
        '200':
          description: A list of articles
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ArticleDto'

  /articles/{artNo}:
    get:
      summary: Info for a specific Article
      operationId: getProductByArtNo
      parameters:
        - name: artNo
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Article found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ArticleDto'
        '404':
          description: Article not found

components:
  schemas:
    ArticleDto:
      type: object
      required:
        - id
        - name
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        tag:
          type: string
