openapi: 3.0.0
info:
  title: Article API
  version: 1.0.0

paths:
  /articles:
    get:
      summary: List all articles
      operationId: getArticles
      tags:
        - articles
      parameters:
        - name: limit
          in: query
          required: false
          schema:
            type: integer
      responses:
        '200':
          description: A list of articles
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ArticleDto'
    post:
      tags:
        - articles
      summary: Add a new article to the store
      description: ''
      operationId: createArticle
      responses:
        '200':
          description: successful operation
          content:
            application/xml:
              schema:
                $ref: '#/components/schemas/ArticleDto'
            application/json:
              schema:
                $ref: '#/components/schemas/ArticleDto'
        '405':
          description: Invalid input

      requestBody:
        $ref: '#/components/requestBodies/ArticleDto'

  /articles/{artNo}:
    get:
      summary: Info for a specific Article
      operationId: getProductByArtNo
      parameters:
        - name: artNo
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Article found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ArticleDto'
        '404':
          description: Article not found

components:
  schemas:
    ArticleDto:
      type: object
      required:
        - id
        - name
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        tag:
          type: string

  requestBodies:

    ArticleDto:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ArticleDto'
        application/xml:
          schema:
            $ref: '#/components/schemas/ArticleDto'
      description: Article object that needs to be added to the store
      required: true
